# Generated by Django 5.0.4 on 2024-08-17 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestedUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unblocked_url", models.URLField(blank=True, null=True)),
                ("visited_at", models.DateTimeField()),
                ("rejected", models.BooleanField(default=False)),
                (
                    "url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protect.restrictedurl",
                    ),
                ),
            ],
        ),
    ]
