# Generated by Django 5.0.4 on 2024-08-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protect", "0002_requestedurls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestedurls",
            name="visited_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
