# Generated by Django 5.1.7 on 2025-06-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0003_alter_requestedurls_visited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestedurls',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protect.restrictedkeyword'),
        ),
    ]
